### ISSUE TITLE
Use different productId for BLE device

### ISSUE THREAD

**Issue by ert78gb** [UltimateHackingKeyboard/firmware#946]
Related story: https://github.com/UltimateHackingKeyboard/agent/issues/2389

When an UHK80 keyboard connects to the computer via Bluetooth LE (BLE) then the keyboard available as USB HID devices. 
Agent recognise the UHK keyboard and starts to communicate with it, but the firmware currently does not support the UHK communication commands on the BLE endpoint. 

The USB HID descriptor contains only the following information 
```javascript
{
    vendorId: 14248,
    productId: 9,
    path: 'DevSrvsID:4294980326',
    serialNumber: '',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'UHK 80',
    release: 1,
    interface: -1,
    usagePage: 65280,
    usage: 1
}
```
Based on these information Agent can't differentiate the keyboard connected via USB or BLE. 
There is no unified way to determine the "source" of the HID device on all 3 main OSs (Linux, Mac, Windows), so possible solution is to use different `productId` (`pid`) for each communication channel.

## Tasks
- [ ] User different `pid` in BLE USB descriptor. The BLE `pid` is USB `pid` + 32768. 
- [ ] Fill the `serialNumber` field in BLE USB descriptor
- [ ] Investigate if we use the same `vid`, `serialNumber` but different `pid` then it cause any issue on any operation system. Based on windows does not like space as `serialNumber`

**Comment by mondalaci** [comment]
Using separate PIDs for BLE vs USB seems possible. I suggest adding a new `CONFIG_USB_PID` Kconfig variable and use it instead of `CONFIG_BT_DIS_PNP_PID` at https://github.com/UltimateHackingKeyboard/firmware-uhk80/blob/ca15f64eab61a5b01d1166d215c9cd4925b6ce2a/device/src/usb/usb.cpp#L41C5-L41C26

Then add the new Kconfig variable in `uhk-{dongle,80-left,80-right}.prj.conf` with the mentioned values.

**Comment by benedekkupper** [comment]
Isn't the serial number only present on USB, and empty on BLE? Couldn't we use that distinguishing factor?

Also, if there are no plans to use the agent HID interface, I can simply remove it from BLE, and keep it on USB only.

**Comment by mondalaci** [comment]
We want the same serial number exposed on both USB and BLE. Per the above specification, we need a different PID for BLE.

Agent will use the BLE interface when USB is absent, so please don't remove it.

**Comment by benedekkupper** [comment]
FYI setting the serial number over BLE in Zephyr can only be done in a hardcoded way: `CONFIG_BT_DIS_SERIAL_NUMBER_STR`. However, it wouldn't take much to replicate the DIS service ourselves with more configurable input parameters.

**Comment by mondalaci** [comment]
Done by UltimateHackingKeyboard/firmware-uhk80#319.
